services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_BASE_URL}
    networks:
      - todolist-client-network

networks:
  todolist-client-network:
    driver: bridge
