export const errorCodes = {

    // Validation DTO and unknown server errors.
    VALIDATION_ERROR: 1001,
    INTERNAL_SERVER_ERROR: 1002,

    // Authentication errors.
    USER_ALREADY_EXISTS: 2001,
    USER_NOT_FOUND: 2002,
    INVALID_PASSWORD: 2003,

    API_AUTH_REGISTER_ERROR: 2101,
    API_AUTH_LOGIN_ERROR: 2102,
    API_AUTH_LOGOUT_ERROR: 2103,
    API_AUTH_UNAUTHORIZED: 2104,

    // List errors.
    LIST_NOT_FOUND: 3001,
    NOT_OWNER_OF_LIST: 3002,

    API_LIST_CREATE_ERROR: 3101,
    API_LIST_EDIT_ERROR: 3102,
    API_LIST_PAGINATION_ERROR: 3103,
    API_LIST_GET_BY_ID_ERROR: 3104,
    API_LIST_DELETE_BY_ID_ERROR: 3105,
}